# Node 2 Configuration (Follower Replica)
cluster.id=hermes-prod-cluster-01
node.id=2
role=follower
listeners=PLAINTEXT://127.0.0.1:9093
log.dirs=./data_node2
logs.dir=./logs_node2
max.segment.bytes=10485760
index.interval.bytes=4096
replica.peer.addresses=127.0.0.1:9092,127.0.0.1:9094
min.insync.replicas=1
log.retention.bytes=104857600
log.retention.ms=86400000
